// Code generated by generator, DO NOT EDIT.
package event

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// CreateEvent inserts a new Event into the database.
func (r *CommandRepository) Create(ctx context.Context, event *Event) error {
	model := Converter(*event)
	query, args := sq.Insert(TableEvent).
		Columns(ColumnEventID, ColumnEventPayload, ColumnEventCreatedAt).
		Values(model.Values()...).PlaceholderFormat(sq.Question).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}
