// Code generated by generator, DO NOT EDIT.
package event

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// GetEvent retrieves a Event by ID.
func (r *CommandRepository) Get(ctx context.Context, opts ...FilterOpt) (*Event, error) {
	b := sq.Select(
		ColumnEventID,
		ColumnEventPayload,
		ColumnEventCreatedAt,
	).
		From(TableEvent).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)

	query, args := b.MustSql()

	var event Event
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&event.ID,
		&event.Payload,
		&event.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w", query, args, err)
	}

	return &event, err
}
func (r *QueryRepository) Get(ctx context.Context, opts ...FilterOpt) (*Event, error) {
	b := sq.Select(
		ColumnEventID,
		ColumnEventPayload,
		ColumnEventCreatedAt,
	).
		From(TableEvent).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)

	query, args := b.MustSql()

	var event Event
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&event.ID,
		&event.Payload,
		&event.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w", query, args, err)
	}

	return &event, err
}

// GetManyEvent retrieves a Event by filter.
func (r *CommandRepository) GetMany(ctx context.Context, opts ...FilterOpt) (Events, error) {
	b := sq.Select(
		ColumnEventID,
		ColumnEventPayload,
		ColumnEventCreatedAt,
	).From(TableEvent).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)
	query, args := b.MustSql()
	var events Events

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()

	var eventModel EventModel
	for rows.Next() {
		err := rows.Scan(
			&eventModel.ID,
			&eventModel.Payload,
			&eventModel.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		events = append(events, ReverseConverter(eventModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return events, err
}

// GetManyEvent retrieves a Event by filter.
func (r *QueryRepository) GetMany(ctx context.Context, opts ...FilterOpt) (Events, error) {
	b := sq.Select(
		ColumnEventID,
		ColumnEventPayload,
		ColumnEventCreatedAt,
	).From(TableEvent).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)
	query, args := b.MustSql()
	var events Events

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()

	var eventModel EventModel
	for rows.Next() {
		err := rows.Scan(
			&eventModel.ID,
			&eventModel.Payload,
			&eventModel.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		events = append(events, ReverseConverter(eventModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return events, err
}
