// Code generated by generator, DO NOT EDIT.
package event

import (
	"sort"
	"time"

	common "github.com/AugustineAurelius/fuufu/pkg/common"
	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)

type CommandRepository struct {
	db common.Querier
}

type QueryRepository struct {
	db common.Querier
}

func NewCommand(db common.Querier) *CommandRepository {
	return &CommandRepository{
		db: db,
	}
}

func NewQuery(db common.Querier) *QueryRepository {
	return &QueryRepository{
		db: db,
	}
}

// EventFiler represents the Event filter.
type Filter struct {
	id            *uuid.UUID
	notid         *uuid.UUID
	gtid          *uuid.UUID
	ltid          *uuid.UUID
	gteqid        *uuid.UUID
	lteqid        *uuid.UUID
	ids           []uuid.UUID
	payload       *[]byte
	notpayload    *[]byte
	gtpayload     *[]byte
	ltpayload     *[]byte
	gteqpayload   *[]byte
	lteqpayload   *[]byte
	payloads      [][]byte
	createdat     *time.Time
	notcreatedat  *time.Time
	gtcreatedat   *time.Time
	ltcreatedat   *time.Time
	gteqcreatedat *time.Time
	lteqcreatedat *time.Time
	createdats    []time.Time
}

type FilterOpt func(f *Filter)

func NewFilter(opts ...FilterOpt) Filter {
	f := &Filter{}
	for _, opt := range opts {
		opt(f)
	}
	return *f
}
func WithID(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.id = &id
	}
}
func WithIDNot(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.notid = &id
	}
}
func WithIDMoreThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.gtid = &id
	}
}
func WithIDLowerThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.ltid = &id
	}
}
func WithIDMoreOrEqualThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.gteqid = &id
	}
}
func WithIDLowerOrEqualThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.lteqid = &id
	}
}
func WithIDs(ids ...uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.ids = append(f.ids, ids...)
	}
}
func WithPayload(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.payload = &payload
	}
}
func WithPayloadNot(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.notpayload = &payload
	}
}
func WithPayloadMoreThen(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.gtpayload = &payload
	}
}
func WithPayloadLowerThen(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.ltpayload = &payload
	}
}
func WithPayloadMoreOrEqualThen(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.gteqpayload = &payload
	}
}
func WithPayloadLowerOrEqualThen(payload []byte) FilterOpt {
	return func(f *Filter) {
		f.lteqpayload = &payload
	}
}
func WithPayloads(payloads ...[]byte) FilterOpt {
	return func(f *Filter) {
		f.payloads = append(f.payloads, payloads...)
	}
}
func WithCreatedAt(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.createdat = &createdat
	}
}
func WithCreatedAtNot(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.notcreatedat = &createdat
	}
}
func WithCreatedAtMoreThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.gtcreatedat = &createdat
	}
}
func WithCreatedAtLowerThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.ltcreatedat = &createdat
	}
}
func WithCreatedAtMoreOrEqualThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.gteqcreatedat = &createdat
	}
}
func WithCreatedAtLowerOrEqualThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.lteqcreatedat = &createdat
	}
}
func WithCreatedAts(createdats ...time.Time) FilterOpt {
	return func(f *Filter) {
		f.createdats = append(f.createdats, createdats...)
	}
}

func ApplyWhere[B interface {
	Where(pred interface{}, args ...interface{}) B
}](b B, f Filter) B {
	if f.id != nil {
		b = b.Where(sq.Eq{ColumnEventID: *f.id})
	}
	if f.notid != nil {
		b = b.Where(sq.NotEq{ColumnEventID: *f.id})
	}
	if f.ltid != nil {
		b = b.Where(sq.Lt{ColumnEventID: *f.id})
	}
	if f.gtid != nil {
		b = b.Where(sq.Gt{ColumnEventID: *f.id})
	}
	if f.lteqid != nil {
		b = b.Where(sq.LtOrEq{ColumnEventID: *f.id})
	}
	if f.gteqid != nil {
		b = b.Where(sq.GtOrEq{ColumnEventID: *f.id})
	}
	if f.ids != nil {
		b = b.Where(sq.Eq{ColumnEventID: f.ids})
	}
	if f.payload != nil {
		b = b.Where(sq.Eq{ColumnEventPayload: *f.payload})
	}
	if f.notpayload != nil {
		b = b.Where(sq.NotEq{ColumnEventPayload: *f.payload})
	}
	if f.ltpayload != nil {
		b = b.Where(sq.Lt{ColumnEventPayload: *f.payload})
	}
	if f.gtpayload != nil {
		b = b.Where(sq.Gt{ColumnEventPayload: *f.payload})
	}
	if f.lteqpayload != nil {
		b = b.Where(sq.LtOrEq{ColumnEventPayload: *f.payload})
	}
	if f.gteqpayload != nil {
		b = b.Where(sq.GtOrEq{ColumnEventPayload: *f.payload})
	}
	if f.payloads != nil {
		b = b.Where(sq.Eq{ColumnEventPayload: f.payloads})
	}
	if f.createdat != nil {
		b = b.Where(sq.Eq{ColumnEventCreatedAt: *f.createdat})
	}
	if f.notcreatedat != nil {
		b = b.Where(sq.NotEq{ColumnEventCreatedAt: *f.createdat})
	}
	if f.ltcreatedat != nil {
		b = b.Where(sq.Lt{ColumnEventCreatedAt: *f.createdat})
	}
	if f.gtcreatedat != nil {
		b = b.Where(sq.Gt{ColumnEventCreatedAt: *f.createdat})
	}
	if f.lteqcreatedat != nil {
		b = b.Where(sq.LtOrEq{ColumnEventCreatedAt: *f.createdat})
	}
	if f.gteqcreatedat != nil {
		b = b.Where(sq.GtOrEq{ColumnEventCreatedAt: *f.createdat})
	}
	if f.createdats != nil {
		b = b.Where(sq.Eq{ColumnEventCreatedAt: f.createdats})
	}
	return b
}

type UpdateOpt func(u *Update)

// EventUpdate represents the Event update struct.
type Update struct {
	id        *uuid.UUID
	payload   *[]byte
	createdat *time.Time
}

func NewUpdate(opts ...UpdateOpt) Update {
	u := &Update{}
	for _, opt := range opts {
		opt(u)
	}
	return *u
}
func WithUpdateID(id uuid.UUID) UpdateOpt {
	return func(f *Update) {
		f.id = &id
	}
}
func WithUpdatePayload(payload []byte) UpdateOpt {
	return func(f *Update) {
		f.payload = &payload
	}
}
func WithUpdateCreatedAt(createdat time.Time) UpdateOpt {
	return func(f *Update) {
		f.createdat = &createdat
	}
}

func ApplySet[B interface {
	Set(column string, value interface{}) B
}](b B, f Update) B {
	if f.id != nil {
		b = b.Set(ColumnEventID, *f.id)
	}
	if f.payload != nil {
		b = b.Set(ColumnEventPayload, *f.payload)
	}
	if f.createdat != nil {
		b = b.Set(ColumnEventCreatedAt, *f.createdat)
	}

	return b
}

type Events []Event

func (s Events) ToIDs() []uuid.UUID {
	output := make([]uuid.UUID, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].ID)
	}
	return output
}
func (s Events) ToPayloads() [][]byte {
	output := make([][]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Payload)
	}
	return output
}
func (s Events) ToCreatedAts() []time.Time {
	output := make([]time.Time, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].CreatedAt)
	}
	return output
}
func (s Events) FindByID(finder uuid.UUID) (Event, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].ID == finder {
			return s[i], true
		}
	}
	return Event{}, false
}
func (s Events) FindByCreatedAt(finder time.Time) (Event, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].CreatedAt == finder {
			return s[i], true
		}
	}
	return Event{}, false
}
func (s Events) SortByCreatedAt(asc bool) Events {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].CreatedAt.Before(s[j].CreatedAt)
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].CreatedAt.After(s[j].CreatedAt)
	})
	return s
}

func (s Events) FilterFunc(f func(i Event) bool) Events {
	output := make(Events, 0, len(s))
	for i := 0; i < len(s); i++ {
		if f(s[i]) {
			output = append(output, s[i])
		}
	}
	return output
}
func (s Events) GetFirstID() (*uuid.UUID, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].ID, true
}
func (s Events) GetFirstPayload() (*[]byte, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Payload, true
}
func (s Events) GetFirstCreatedAt() (*time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].CreatedAt, true
}

func (s Events) GetFirst() (Event, bool) {
	if len(s) < 1 {
		return Event{}, false
	}
	return s[0], true
}
