// Code generated by generator, DO NOT EDIT.
package event

import (
	"time"

	"github.com/google/uuid"
)

// Table and column name constants for Event
const (
	TableEvent           = "events"
	ColumnEventID        = "id"
	ColumnEventPayload   = "payload"
	ColumnEventCreatedAt = "created_at"
)

// Event represents the Event message.
type EventModel struct {
	ID string

	Payload []byte

	CreatedAt time.Time
}

func (m EventModel) Values() []any {
	return []any{
		m.ID,
		m.Payload,
		m.CreatedAt,
	}
}

func Converter(event Event) EventModel {
	return EventModel{

		ID: event.ID.String(),

		Payload: event.Payload,

		CreatedAt: event.CreatedAt,
	}
}

func ReverseConverter(eventModel EventModel) Event {
	return Event{

		ID: uuid.MustParse(eventModel.ID),

		Payload: eventModel.Payload,

		CreatedAt: eventModel.CreatedAt,
	}
}
