// Code generated by generator, DO NOT EDIT.
package todo

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// CreateTask inserts a new Task into the database.
func (r *Repository) Create(ctx context.Context, task *Task) error {
	model := Converter(*task)
	query, args := sq.Insert(TableTask).
		Columns(ColumnTaskID, ColumnTaskName, ColumnTaskDescription, ColumnTaskCreatedBy, ColumnTaskDoer, ColumnTaskDone, ColumnTaskRepeatable, ColumnTaskRepeatAfter, ColumnTaskDoBefore, ColumnTaskCreatedAt, ColumnTaskUpdatedAt).
		Values(model.Values()...).PlaceholderFormat(sq.Question).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}
