// Code generated by generator, DO NOT EDIT.
package todo

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// DeleteTask deletes a Task by ID.
func (r *CommandRepository) Delete(ctx context.Context, opts ...FilterOpt) error {
	b := sq.Delete(TableTask).PlaceholderFormat(sq.Question)
	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)
	query, args := b.MustSql()
	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec delete query %s with args %v error = %w", query, args, err)
	}
	return nil
}
