// Code generated by generator, DO NOT EDIT.
package todo

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)

// GetTask retrieves a Task by ID.
func (r *Repository) Get(ctx context.Context, id uuid.UUID) (*Task, error) {
	query, args := sq.Select(
		ColumnTaskID,
		ColumnTaskName,
		ColumnTaskDescription,
		ColumnTaskCreatedBy,
		ColumnTaskDoer,
		ColumnTaskDone,
		ColumnTaskRepeatable,
		ColumnTaskRepeatAfter,
		ColumnTaskDoBefore,
		ColumnTaskCreatedAt,
		ColumnTaskUpdatedAt,
	).
		From(TableTask).
		Where(sq.Eq{ColumnTaskID: id}).PlaceholderFormat(sq.Question).MustSql()

	var task Task
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&task.ID,
		&task.Name,
		&task.Description,
		&task.CreatedBy,
		&task.Doer,
		&task.Done,
		&task.Repeatable,
		&task.RepeatAfter,
		&task.DoBefore,
		&task.CreatedAt,
		&task.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w", query, args, err)
	}

	return &task, err
}

// GetManyTask retrieves a Task by filter.
func (r *Repository) GetMany(ctx context.Context, f Filter) (Tasks, error) {
	b := sq.Select(
		ColumnTaskID,
		ColumnTaskName,
		ColumnTaskDescription,
		ColumnTaskCreatedBy,
		ColumnTaskDoer,
		ColumnTaskDone,
		ColumnTaskRepeatable,
		ColumnTaskRepeatAfter,
		ColumnTaskDoBefore,
		ColumnTaskCreatedAt,
		ColumnTaskUpdatedAt,
	).From(TableTask).PlaceholderFormat(sq.Question)

	b = ApplyWhere(b, f)

	query, args := b.MustSql()

	var tasks Tasks

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()

	var taskModel TaskModel
	for rows.Next() {
		err := rows.Scan(
			&taskModel.ID,
			&taskModel.Name,
			&taskModel.Description,
			&taskModel.CreatedBy,
			&taskModel.Doer,
			&taskModel.Done,
			&taskModel.Repeatable,
			&taskModel.RepeatAfter,
			&taskModel.DoBefore,
			&taskModel.CreatedAt,
			&taskModel.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		tasks = append(tasks, ReverseConverter(taskModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return tasks, err
}
