// Code generated by generator, DO NOT EDIT.
package todo

import (
	"sort"
	"time"

	common "github.com/AugustineAurelius/fuufu/pkg/common"
	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)

type CommandRepository struct {
	db common.Querier
}

type QueryRepository struct {
	db common.Querier
}

func NewCommand(db common.Querier) *CommandRepository {
	return &CommandRepository{
		db: db,
	}
}

func NewQuery(db common.Querier) *QueryRepository {
	return &QueryRepository{
		db: db,
	}
}

// TaskFiler represents the Task filter.
type Filter struct {
	id              *uuid.UUID
	notid           *uuid.UUID
	gtid            *uuid.UUID
	ltid            *uuid.UUID
	gteqid          *uuid.UUID
	lteqid          *uuid.UUID
	ids             []uuid.UUID
	name            *string
	notname         *string
	gtname          *string
	ltname          *string
	gteqname        *string
	lteqname        *string
	names           []string
	description     **string
	notdescription  **string
	gtdescription   **string
	ltdescription   **string
	gteqdescription **string
	lteqdescription **string
	descriptions    []*string
	createdby       *string
	notcreatedby    *string
	gtcreatedby     *string
	ltcreatedby     *string
	gteqcreatedby   *string
	lteqcreatedby   *string
	createdbys      []string
	doer            *string
	notdoer         *string
	gtdoer          *string
	ltdoer          *string
	gteqdoer        *string
	lteqdoer        *string
	doers           []string
	done            *bool
	notdone         *bool
	gtdone          *bool
	ltdone          *bool
	gteqdone        *bool
	lteqdone        *bool
	dones           []bool
	repeatable      *bool
	notrepeatable   *bool
	gtrepeatable    *bool
	ltrepeatable    *bool
	gteqrepeatable  *bool
	lteqrepeatable  *bool
	repeatables     []bool
	repeatafter     **int
	notrepeatafter  **int
	gtrepeatafter   **int
	ltrepeatafter   **int
	gteqrepeatafter **int
	lteqrepeatafter **int
	repeatafters    []*int
	dobefore        **time.Time
	notdobefore     **time.Time
	gtdobefore      **time.Time
	ltdobefore      **time.Time
	gteqdobefore    **time.Time
	lteqdobefore    **time.Time
	dobefores       []*time.Time
	createdat       *time.Time
	notcreatedat    *time.Time
	gtcreatedat     *time.Time
	ltcreatedat     *time.Time
	gteqcreatedat   *time.Time
	lteqcreatedat   *time.Time
	createdats      []time.Time
	updatedat       **time.Time
	notupdatedat    **time.Time
	gtupdatedat     **time.Time
	ltupdatedat     **time.Time
	gtequpdatedat   **time.Time
	ltequpdatedat   **time.Time
	updatedats      []*time.Time
}

type FilterOpt func(f *Filter)

func NewFilter(opts ...FilterOpt) Filter {
	f := &Filter{}
	for _, opt := range opts {
		opt(f)
	}
	return *f
}
func WithID(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.id = &id
	}
}
func WithIDNot(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.notid = &id
	}
}
func WithIDMoreThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.gtid = &id
	}
}
func WithIDLowerThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.ltid = &id
	}
}
func WithIDMoreOrEqualThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.gteqid = &id
	}
}
func WithIDLowerOrEqualThen(id uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.lteqid = &id
	}
}
func WithIDs(ids ...uuid.UUID) FilterOpt {
	return func(f *Filter) {
		f.ids = append(f.ids, ids...)
	}
}
func WithName(name string) FilterOpt {
	return func(f *Filter) {
		f.name = &name
	}
}
func WithNameNot(name string) FilterOpt {
	return func(f *Filter) {
		f.notname = &name
	}
}
func WithNameMoreThen(name string) FilterOpt {
	return func(f *Filter) {
		f.gtname = &name
	}
}
func WithNameLowerThen(name string) FilterOpt {
	return func(f *Filter) {
		f.ltname = &name
	}
}
func WithNameMoreOrEqualThen(name string) FilterOpt {
	return func(f *Filter) {
		f.gteqname = &name
	}
}
func WithNameLowerOrEqualThen(name string) FilterOpt {
	return func(f *Filter) {
		f.lteqname = &name
	}
}
func WithNames(names ...string) FilterOpt {
	return func(f *Filter) {
		f.names = append(f.names, names...)
	}
}
func WithDescription(description *string) FilterOpt {
	return func(f *Filter) {
		f.description = &description
	}
}
func WithDescriptionNot(description *string) FilterOpt {
	return func(f *Filter) {
		f.notdescription = &description
	}
}
func WithDescriptionMoreThen(description *string) FilterOpt {
	return func(f *Filter) {
		f.gtdescription = &description
	}
}
func WithDescriptionLowerThen(description *string) FilterOpt {
	return func(f *Filter) {
		f.ltdescription = &description
	}
}
func WithDescriptionMoreOrEqualThen(description *string) FilterOpt {
	return func(f *Filter) {
		f.gteqdescription = &description
	}
}
func WithDescriptionLowerOrEqualThen(description *string) FilterOpt {
	return func(f *Filter) {
		f.lteqdescription = &description
	}
}
func WithDescriptions(descriptions ...*string) FilterOpt {
	return func(f *Filter) {
		f.descriptions = append(f.descriptions, descriptions...)
	}
}
func WithCreatedBy(createdby string) FilterOpt {
	return func(f *Filter) {
		f.createdby = &createdby
	}
}
func WithCreatedByNot(createdby string) FilterOpt {
	return func(f *Filter) {
		f.notcreatedby = &createdby
	}
}
func WithCreatedByMoreThen(createdby string) FilterOpt {
	return func(f *Filter) {
		f.gtcreatedby = &createdby
	}
}
func WithCreatedByLowerThen(createdby string) FilterOpt {
	return func(f *Filter) {
		f.ltcreatedby = &createdby
	}
}
func WithCreatedByMoreOrEqualThen(createdby string) FilterOpt {
	return func(f *Filter) {
		f.gteqcreatedby = &createdby
	}
}
func WithCreatedByLowerOrEqualThen(createdby string) FilterOpt {
	return func(f *Filter) {
		f.lteqcreatedby = &createdby
	}
}
func WithCreatedBys(createdbys ...string) FilterOpt {
	return func(f *Filter) {
		f.createdbys = append(f.createdbys, createdbys...)
	}
}
func WithDoer(doer string) FilterOpt {
	return func(f *Filter) {
		f.doer = &doer
	}
}
func WithDoerNot(doer string) FilterOpt {
	return func(f *Filter) {
		f.notdoer = &doer
	}
}
func WithDoerMoreThen(doer string) FilterOpt {
	return func(f *Filter) {
		f.gtdoer = &doer
	}
}
func WithDoerLowerThen(doer string) FilterOpt {
	return func(f *Filter) {
		f.ltdoer = &doer
	}
}
func WithDoerMoreOrEqualThen(doer string) FilterOpt {
	return func(f *Filter) {
		f.gteqdoer = &doer
	}
}
func WithDoerLowerOrEqualThen(doer string) FilterOpt {
	return func(f *Filter) {
		f.lteqdoer = &doer
	}
}
func WithDoers(doers ...string) FilterOpt {
	return func(f *Filter) {
		f.doers = append(f.doers, doers...)
	}
}
func WithDone(done bool) FilterOpt {
	return func(f *Filter) {
		f.done = &done
	}
}
func WithDoneNot(done bool) FilterOpt {
	return func(f *Filter) {
		f.notdone = &done
	}
}
func WithDoneMoreThen(done bool) FilterOpt {
	return func(f *Filter) {
		f.gtdone = &done
	}
}
func WithDoneLowerThen(done bool) FilterOpt {
	return func(f *Filter) {
		f.ltdone = &done
	}
}
func WithDoneMoreOrEqualThen(done bool) FilterOpt {
	return func(f *Filter) {
		f.gteqdone = &done
	}
}
func WithDoneLowerOrEqualThen(done bool) FilterOpt {
	return func(f *Filter) {
		f.lteqdone = &done
	}
}
func WithDones(dones ...bool) FilterOpt {
	return func(f *Filter) {
		f.dones = append(f.dones, dones...)
	}
}
func WithRepeatable(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.repeatable = &repeatable
	}
}
func WithRepeatableNot(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.notrepeatable = &repeatable
	}
}
func WithRepeatableMoreThen(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.gtrepeatable = &repeatable
	}
}
func WithRepeatableLowerThen(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.ltrepeatable = &repeatable
	}
}
func WithRepeatableMoreOrEqualThen(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.gteqrepeatable = &repeatable
	}
}
func WithRepeatableLowerOrEqualThen(repeatable bool) FilterOpt {
	return func(f *Filter) {
		f.lteqrepeatable = &repeatable
	}
}
func WithRepeatables(repeatables ...bool) FilterOpt {
	return func(f *Filter) {
		f.repeatables = append(f.repeatables, repeatables...)
	}
}
func WithRepeatAfter(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.repeatafter = &repeatafter
	}
}
func WithRepeatAfterNot(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.notrepeatafter = &repeatafter
	}
}
func WithRepeatAfterMoreThen(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.gtrepeatafter = &repeatafter
	}
}
func WithRepeatAfterLowerThen(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.ltrepeatafter = &repeatafter
	}
}
func WithRepeatAfterMoreOrEqualThen(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.gteqrepeatafter = &repeatafter
	}
}
func WithRepeatAfterLowerOrEqualThen(repeatafter *int) FilterOpt {
	return func(f *Filter) {
		f.lteqrepeatafter = &repeatafter
	}
}
func WithRepeatAfters(repeatafters ...*int) FilterOpt {
	return func(f *Filter) {
		f.repeatafters = append(f.repeatafters, repeatafters...)
	}
}
func WithDoBefore(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.dobefore = &dobefore
	}
}
func WithDoBeforeNot(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.notdobefore = &dobefore
	}
}
func WithDoBeforeMoreThen(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.gtdobefore = &dobefore
	}
}
func WithDoBeforeLowerThen(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.ltdobefore = &dobefore
	}
}
func WithDoBeforeMoreOrEqualThen(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.gteqdobefore = &dobefore
	}
}
func WithDoBeforeLowerOrEqualThen(dobefore *time.Time) FilterOpt {
	return func(f *Filter) {
		f.lteqdobefore = &dobefore
	}
}
func WithDoBefores(dobefores ...*time.Time) FilterOpt {
	return func(f *Filter) {
		f.dobefores = append(f.dobefores, dobefores...)
	}
}
func WithCreatedAt(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.createdat = &createdat
	}
}
func WithCreatedAtNot(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.notcreatedat = &createdat
	}
}
func WithCreatedAtMoreThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.gtcreatedat = &createdat
	}
}
func WithCreatedAtLowerThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.ltcreatedat = &createdat
	}
}
func WithCreatedAtMoreOrEqualThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.gteqcreatedat = &createdat
	}
}
func WithCreatedAtLowerOrEqualThen(createdat time.Time) FilterOpt {
	return func(f *Filter) {
		f.lteqcreatedat = &createdat
	}
}
func WithCreatedAts(createdats ...time.Time) FilterOpt {
	return func(f *Filter) {
		f.createdats = append(f.createdats, createdats...)
	}
}
func WithUpdatedAt(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.updatedat = &updatedat
	}
}
func WithUpdatedAtNot(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.notupdatedat = &updatedat
	}
}
func WithUpdatedAtMoreThen(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.gtupdatedat = &updatedat
	}
}
func WithUpdatedAtLowerThen(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.ltupdatedat = &updatedat
	}
}
func WithUpdatedAtMoreOrEqualThen(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.gtequpdatedat = &updatedat
	}
}
func WithUpdatedAtLowerOrEqualThen(updatedat *time.Time) FilterOpt {
	return func(f *Filter) {
		f.ltequpdatedat = &updatedat
	}
}
func WithUpdatedAts(updatedats ...*time.Time) FilterOpt {
	return func(f *Filter) {
		f.updatedats = append(f.updatedats, updatedats...)
	}
}

func ApplyWhere[B interface {
	Where(pred interface{}, args ...interface{}) B
}](b B, f Filter) B {
	if f.id != nil {
		b = b.Where(sq.Eq{ColumnTaskID: *f.id})
	}
	if f.notid != nil {
		b = b.Where(sq.NotEq{ColumnTaskID: *f.id})
	}
	if f.ltid != nil {
		b = b.Where(sq.Lt{ColumnTaskID: *f.id})
	}
	if f.gtid != nil {
		b = b.Where(sq.Gt{ColumnTaskID: *f.id})
	}
	if f.lteqid != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskID: *f.id})
	}
	if f.gteqid != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskID: *f.id})
	}
	if f.ids != nil {
		b = b.Where(sq.Eq{ColumnTaskID: f.ids})
	}
	if f.name != nil {
		b = b.Where(sq.Eq{ColumnTaskName: *f.name})
	}
	if f.notname != nil {
		b = b.Where(sq.NotEq{ColumnTaskName: *f.name})
	}
	if f.ltname != nil {
		b = b.Where(sq.Lt{ColumnTaskName: *f.name})
	}
	if f.gtname != nil {
		b = b.Where(sq.Gt{ColumnTaskName: *f.name})
	}
	if f.lteqname != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskName: *f.name})
	}
	if f.gteqname != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskName: *f.name})
	}
	if f.names != nil {
		b = b.Where(sq.Eq{ColumnTaskName: f.names})
	}
	if f.description != nil {
		b = b.Where(sq.Eq{ColumnTaskDescription: *f.description})
	}
	if f.notdescription != nil {
		b = b.Where(sq.NotEq{ColumnTaskDescription: *f.description})
	}
	if f.ltdescription != nil {
		b = b.Where(sq.Lt{ColumnTaskDescription: *f.description})
	}
	if f.gtdescription != nil {
		b = b.Where(sq.Gt{ColumnTaskDescription: *f.description})
	}
	if f.lteqdescription != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskDescription: *f.description})
	}
	if f.gteqdescription != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskDescription: *f.description})
	}
	if f.descriptions != nil {
		b = b.Where(sq.Eq{ColumnTaskDescription: f.descriptions})
	}
	if f.createdby != nil {
		b = b.Where(sq.Eq{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.notcreatedby != nil {
		b = b.Where(sq.NotEq{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.ltcreatedby != nil {
		b = b.Where(sq.Lt{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.gtcreatedby != nil {
		b = b.Where(sq.Gt{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.lteqcreatedby != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.gteqcreatedby != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskCreatedBy: *f.createdby})
	}
	if f.createdbys != nil {
		b = b.Where(sq.Eq{ColumnTaskCreatedBy: f.createdbys})
	}
	if f.doer != nil {
		b = b.Where(sq.Eq{ColumnTaskDoer: *f.doer})
	}
	if f.notdoer != nil {
		b = b.Where(sq.NotEq{ColumnTaskDoer: *f.doer})
	}
	if f.ltdoer != nil {
		b = b.Where(sq.Lt{ColumnTaskDoer: *f.doer})
	}
	if f.gtdoer != nil {
		b = b.Where(sq.Gt{ColumnTaskDoer: *f.doer})
	}
	if f.lteqdoer != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskDoer: *f.doer})
	}
	if f.gteqdoer != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskDoer: *f.doer})
	}
	if f.doers != nil {
		b = b.Where(sq.Eq{ColumnTaskDoer: f.doers})
	}
	if f.done != nil {
		b = b.Where(sq.Eq{ColumnTaskDone: *f.done})
	}
	if f.notdone != nil {
		b = b.Where(sq.NotEq{ColumnTaskDone: *f.done})
	}
	if f.ltdone != nil {
		b = b.Where(sq.Lt{ColumnTaskDone: *f.done})
	}
	if f.gtdone != nil {
		b = b.Where(sq.Gt{ColumnTaskDone: *f.done})
	}
	if f.lteqdone != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskDone: *f.done})
	}
	if f.gteqdone != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskDone: *f.done})
	}
	if f.dones != nil {
		b = b.Where(sq.Eq{ColumnTaskDone: f.dones})
	}
	if f.repeatable != nil {
		b = b.Where(sq.Eq{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.notrepeatable != nil {
		b = b.Where(sq.NotEq{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.ltrepeatable != nil {
		b = b.Where(sq.Lt{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.gtrepeatable != nil {
		b = b.Where(sq.Gt{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.lteqrepeatable != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.gteqrepeatable != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskRepeatable: *f.repeatable})
	}
	if f.repeatables != nil {
		b = b.Where(sq.Eq{ColumnTaskRepeatable: f.repeatables})
	}
	if f.repeatafter != nil {
		b = b.Where(sq.Eq{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.notrepeatafter != nil {
		b = b.Where(sq.NotEq{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.ltrepeatafter != nil {
		b = b.Where(sq.Lt{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.gtrepeatafter != nil {
		b = b.Where(sq.Gt{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.lteqrepeatafter != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.gteqrepeatafter != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskRepeatAfter: *f.repeatafter})
	}
	if f.repeatafters != nil {
		b = b.Where(sq.Eq{ColumnTaskRepeatAfter: f.repeatafters})
	}
	if f.dobefore != nil {
		b = b.Where(sq.Eq{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.notdobefore != nil {
		b = b.Where(sq.NotEq{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.ltdobefore != nil {
		b = b.Where(sq.Lt{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.gtdobefore != nil {
		b = b.Where(sq.Gt{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.lteqdobefore != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.gteqdobefore != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskDoBefore: *f.dobefore})
	}
	if f.dobefores != nil {
		b = b.Where(sq.Eq{ColumnTaskDoBefore: f.dobefores})
	}
	if f.createdat != nil {
		b = b.Where(sq.Eq{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.notcreatedat != nil {
		b = b.Where(sq.NotEq{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.ltcreatedat != nil {
		b = b.Where(sq.Lt{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.gtcreatedat != nil {
		b = b.Where(sq.Gt{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.lteqcreatedat != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.gteqcreatedat != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskCreatedAt: *f.createdat})
	}
	if f.createdats != nil {
		b = b.Where(sq.Eq{ColumnTaskCreatedAt: f.createdats})
	}
	if f.updatedat != nil {
		b = b.Where(sq.Eq{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.notupdatedat != nil {
		b = b.Where(sq.NotEq{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.ltupdatedat != nil {
		b = b.Where(sq.Lt{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.gtupdatedat != nil {
		b = b.Where(sq.Gt{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.ltequpdatedat != nil {
		b = b.Where(sq.LtOrEq{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.gtequpdatedat != nil {
		b = b.Where(sq.GtOrEq{ColumnTaskUpdatedAt: *f.updatedat})
	}
	if f.updatedats != nil {
		b = b.Where(sq.Eq{ColumnTaskUpdatedAt: f.updatedats})
	}
	return b
}

type UpdateOpt func(u *Update)

// TaskUpdate represents the Task update struct.
type Update struct {
	id          *uuid.UUID
	name        *string
	description **string
	createdby   *string
	doer        *string
	done        *bool
	repeatable  *bool
	repeatafter **int
	dobefore    **time.Time
	createdat   *time.Time
	updatedat   **time.Time
}

func NewUpdate(opts ...UpdateOpt) Update {
	u := &Update{}
	for _, opt := range opts {
		opt(u)
	}
	return *u
}
func WithUpdateID(id uuid.UUID) UpdateOpt {
	return func(f *Update) {
		f.id = &id
	}
}
func WithUpdateName(name string) UpdateOpt {
	return func(f *Update) {
		f.name = &name
	}
}
func WithUpdateDescription(description *string) UpdateOpt {
	return func(f *Update) {
		f.description = &description
	}
}
func WithUpdateCreatedBy(createdby string) UpdateOpt {
	return func(f *Update) {
		f.createdby = &createdby
	}
}
func WithUpdateDoer(doer string) UpdateOpt {
	return func(f *Update) {
		f.doer = &doer
	}
}
func WithUpdateDone(done bool) UpdateOpt {
	return func(f *Update) {
		f.done = &done
	}
}
func WithUpdateRepeatable(repeatable bool) UpdateOpt {
	return func(f *Update) {
		f.repeatable = &repeatable
	}
}
func WithUpdateRepeatAfter(repeatafter *int) UpdateOpt {
	return func(f *Update) {
		f.repeatafter = &repeatafter
	}
}
func WithUpdateDoBefore(dobefore *time.Time) UpdateOpt {
	return func(f *Update) {
		f.dobefore = &dobefore
	}
}
func WithUpdateCreatedAt(createdat time.Time) UpdateOpt {
	return func(f *Update) {
		f.createdat = &createdat
	}
}
func WithUpdateUpdatedAt(updatedat *time.Time) UpdateOpt {
	return func(f *Update) {
		f.updatedat = &updatedat
	}
}

func ApplySet[B interface {
	Set(column string, value interface{}) B
}](b B, f Update) B {
	if f.id != nil {
		b = b.Set(ColumnTaskID, *f.id)
	}
	if f.name != nil {
		b = b.Set(ColumnTaskName, *f.name)
	}
	if f.description != nil {
		b = b.Set(ColumnTaskDescription, *f.description)
	}
	if f.createdby != nil {
		b = b.Set(ColumnTaskCreatedBy, *f.createdby)
	}
	if f.doer != nil {
		b = b.Set(ColumnTaskDoer, *f.doer)
	}
	if f.done != nil {
		b = b.Set(ColumnTaskDone, *f.done)
	}
	if f.repeatable != nil {
		b = b.Set(ColumnTaskRepeatable, *f.repeatable)
	}
	if f.repeatafter != nil {
		b = b.Set(ColumnTaskRepeatAfter, *f.repeatafter)
	}
	if f.dobefore != nil {
		b = b.Set(ColumnTaskDoBefore, *f.dobefore)
	}
	if f.createdat != nil {
		b = b.Set(ColumnTaskCreatedAt, *f.createdat)
	}
	if f.updatedat != nil {
		b = b.Set(ColumnTaskUpdatedAt, *f.updatedat)
	}

	return b
}

type Tasks []Task

func (s Tasks) ToIDs() []uuid.UUID {
	output := make([]uuid.UUID, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].ID)
	}
	return output
}
func (s Tasks) ToNames() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Name)
	}
	return output
}
func (s Tasks) ToDescriptions() []*string {
	output := make([]*string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Description)
	}
	return output
}
func (s Tasks) ToCreatedBys() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].CreatedBy)
	}
	return output
}
func (s Tasks) ToDoers() []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Doer)
	}
	return output
}
func (s Tasks) ToDones() []bool {
	output := make([]bool, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Done)
	}
	return output
}
func (s Tasks) ToRepeatables() []bool {
	output := make([]bool, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].Repeatable)
	}
	return output
}
func (s Tasks) ToRepeatAfters() []*int {
	output := make([]*int, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].RepeatAfter)
	}
	return output
}
func (s Tasks) ToDoBefores() []*time.Time {
	output := make([]*time.Time, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].DoBefore)
	}
	return output
}
func (s Tasks) ToCreatedAts() []time.Time {
	output := make([]time.Time, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].CreatedAt)
	}
	return output
}
func (s Tasks) ToUpdatedAts() []*time.Time {
	output := make([]*time.Time, 0, len(s))
	for i := 0; i < len(s); i++ {
		output = append(output, s[i].UpdatedAt)
	}
	return output
}
func (s Tasks) FindByID(finder uuid.UUID) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].ID == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByName(finder string) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Name == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByDescription(finder *string) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Description == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByCreatedBy(finder string) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].CreatedBy == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByDoer(finder string) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Doer == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByDone(finder bool) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Done == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByRepeatable(finder bool) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].Repeatable == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByRepeatAfter(finder *int) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].RepeatAfter == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByDoBefore(finder *time.Time) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].DoBefore == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByCreatedAt(finder time.Time) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].CreatedAt == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) FindByUpdatedAt(finder *time.Time) (Task, bool) {
	for i := 0; i < len(s); i++ {
		if s[i].UpdatedAt == finder {
			return s[i], true
		}
	}
	return Task{}, false
}
func (s Tasks) SortByName(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].Name < s[j].Name
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].Name > s[j].Name
	})
	return s
}
func (s Tasks) SortByDescription(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return *s[i].Description < *s[j].Description
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return *s[i].Description > *s[j].Description
	})
	return s
}
func (s Tasks) SortByCreatedBy(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].CreatedBy < s[j].CreatedBy
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].CreatedBy > s[j].CreatedBy
	})
	return s
}
func (s Tasks) SortByDoer(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].Doer < s[j].Doer
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].Doer > s[j].Doer
	})
	return s
}
func (s Tasks) SortByRepeatAfter(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return *s[i].RepeatAfter < *s[j].RepeatAfter
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return *s[i].RepeatAfter > *s[j].RepeatAfter
	})
	return s
}
func (s Tasks) SortByDoBefore(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].DoBefore.Before(*s[j].DoBefore)
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].DoBefore.After(*s[j].DoBefore)
	})
	return s
}
func (s Tasks) SortByCreatedAt(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].CreatedAt.Before(s[j].CreatedAt)
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].CreatedAt.After(s[j].CreatedAt)
	})
	return s
}
func (s Tasks) SortByUpdatedAt(asc bool) Tasks {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].UpdatedAt.Before(*s[j].UpdatedAt)
		})
		return s
	}
	sort.Slice(s, func(i, j int) bool {
		return s[i].UpdatedAt.After(*s[j].UpdatedAt)
	})
	return s
}

func (s Tasks) FilterFunc(f func(i Task) bool) Tasks {
	output := make(Tasks, 0, len(s))
	for i := 0; i < len(s); i++ {
		if f(s[i]) {
			output = append(output, s[i])
		}
	}
	return output
}
func (s Tasks) GetFirstID() (*uuid.UUID, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].ID, true
}
func (s Tasks) GetFirstName() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Name, true
}
func (s Tasks) GetFirstDescription() (**string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Description, true
}
func (s Tasks) GetFirstCreatedBy() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].CreatedBy, true
}
func (s Tasks) GetFirstDoer() (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Doer, true
}
func (s Tasks) GetFirstDone() (*bool, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Done, true
}
func (s Tasks) GetFirstRepeatable() (*bool, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Repeatable, true
}
func (s Tasks) GetFirstRepeatAfter() (**int, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].RepeatAfter, true
}
func (s Tasks) GetFirstDoBefore() (**time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].DoBefore, true
}
func (s Tasks) GetFirstCreatedAt() (*time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].CreatedAt, true
}
func (s Tasks) GetFirstUpdatedAt() (**time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].UpdatedAt, true
}

func (s Tasks) GetFirst() (Task, bool) {
	if len(s) < 1 {
		return Task{}, false
	}
	return s[0], true
}
