// Code generated by generator, DO NOT EDIT.
package todo

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)

// UpdateTask updates an existing Task in the database.
func (r *Repository) Update(ctx context.Context, id uuid.UUID, u Update) error {
	b := sq.Update(TableTask).PlaceholderFormat(sq.Question).Where(sq.Eq{ColumnTaskID: id})
	b = ApplySet(b, u)
	query, args := b.MustSql()
	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec update query %s with args %v", query, args)
	}
	return nil
}

// UpdateTask updates an existing Task in the database.
func (r *Repository) UpdateMany(ctx context.Context, f Filter, u Update) error {
	b := sq.Update(TableTask).PlaceholderFormat(sq.Question)

	b = ApplyWhere(b, f)

	b = ApplySet(b, u)

	query, args := b.MustSql()
	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec update query %s with args %v error = %w", query, args, err)
	}
	return nil
}
