// Code generated by generator, DO NOT EDIT.
package common

import (
	"context"
	"regexp"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"go.uber.org/zap"
)

type PostgresConnectionProvider interface {
	URL() string
}

type PostgresDB struct {
	Pool *pgxpool.Pool

	logger logger
}

func NewPostgres(ctx context.Context, provider PostgresConnectionProvider,

	logger logger,

) (PostgresDB, error) {
	url := provider.URL()

	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		return PostgresDB{}, err
	}

	return PostgresDB{Pool: pool,

		logger: logger,
	}, nil
}

func (db *PostgresDB) Close() error {
	db.Pool.Close()
	return nil
}

func (db *PostgresDB) QueryRow(ctx context.Context, query string, args ...any) row {

	start := time.Now()
	db.logger.Info("Executing QueryRow", zap.String("query", query))

	row := db.Pool.QueryRow(ctx, ReplaceQuestions(query), args...)

	duration := time.Since(start).Seconds()
	db.logger.Info("QueryRow succeeded", zap.Float64("duration", duration))

	return &PostgresRow{row}
}

func (db *PostgresDB) Query(ctx context.Context, query string, args ...any) (rows, error) {

	start := time.Now()
	db.logger.Info("Executing Query", zap.String("query", query))

	rows, err := db.Pool.Query(ctx, ReplaceQuestions(query), args...)
	if err != nil {

		db.logger.Error("Query failed", zap.Error(err))

		return nil, err
	}

	duration := time.Since(start).Seconds()
	db.logger.Info("Query succeeded", zap.Float64("duration", duration))

	return &PostgresRows{rows}, nil
}

func (db *PostgresDB) Exec(ctx context.Context, query string, args ...any) (result, error) {

	start := time.Now()
	db.logger.Info("Executing Exec", zap.String("query", query))

	r, err := db.Pool.Exec(ctx, ReplaceQuestions(query), args...)
	if err != nil {

		db.logger.Error("Exec failed", zap.Error(err))

		return nil, err
	}

	duration := time.Since(start).Seconds()
	db.logger.Info("Exec succeeded", zap.Float64("duration", duration))

	return &PostgresResult{r}, err
}

func (db *PostgresDB) BeginTransaction(ctx context.Context) (Tx, error) {
	tx, err := db.Pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	return &PostgresTx{tx}, nil
}

type PostgresRow struct {
	pgx.Row
}

func (db *PostgresRow) Scan(dest ...any) error {
	return db.Row.Scan(dest...)
}

type PostgresRows struct {
	pgx.Rows
}

func (db *PostgresRows) Next() bool {
	return db.Rows.Next()
}

func (db *PostgresRows) Scan(dest ...any) error {
	return db.Rows.Scan(dest...)
}

func (db *PostgresRows) Close() error {
	db.Rows.Close()
	return nil
}

func (db *PostgresRows) Err() error {
	return db.Rows.Err()
}

type PostgresTx struct {
	pgx.Tx
}

func (p *PostgresTx) Query(ctx context.Context, query string, args ...any) (rows, error) {
	rows, err := p.Tx.Query(ctx, ReplaceQuestions(query), args...)
	if err != nil {
		return nil, err
	}
	return &PostgresRows{rows}, nil
}

func (p *PostgresTx) QueryRow(ctx context.Context, query string, args ...any) row {
	return &PostgresRow{p.Tx.QueryRow(ctx, ReplaceQuestions(query), args...)}
}

func (p *PostgresTx) Exec(ctx context.Context, query string, args ...any) (result, error) {
	r, err := p.Tx.Exec(ctx, ReplaceQuestions(query), args...)
	return &PostgresResult{r}, err
}

func (p *PostgresTx) Commit(ctx context.Context) error {
	return p.Tx.Commit(ctx)
}

func (p *PostgresTx) Rollback(ctx context.Context) error {
	return p.Tx.Rollback(ctx)
}

type PostgresResult struct {
	pgconn.CommandTag
}

func (r *PostgresResult) RowsAffected() (int64, error) {
	return r.CommandTag.RowsAffected(), nil
}

func ReplaceQuestions(query string) string {
	var count int
	re := regexp.MustCompile(`\?`)
	return re.ReplaceAllStringFunc(query, func(s string) string {
		count++
		return "$" + strconv.Itoa(count)
	})
}
