//go:build go1.22

// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package auth

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthToken defines model for AuthToken.
type AuthToken struct {
	Expires *time.Time `json:"expires,omitempty"`
	Token   *string    `json:"token,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Username  string             `json:"username"`
}

// PostApiV1AuthSigninJSONBody defines parameters for PostApiV1AuthSignin.
type PostApiV1AuthSigninJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostApiV1AuthSignupJSONBody defines parameters for PostApiV1AuthSignup.
type PostApiV1AuthSignupJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// PostApiV1AuthSigninJSONRequestBody defines body for PostApiV1AuthSignin for application/json ContentType.
type PostApiV1AuthSigninJSONRequestBody PostApiV1AuthSigninJSONBody

// PostApiV1AuthSignupJSONRequestBody defines body for PostApiV1AuthSignup for application/json ContentType.
type PostApiV1AuthSignupJSONRequestBody PostApiV1AuthSignupJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user
	// (POST /api/v1/auth/signin)
	PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request)
	// Register new user
	// (POST /api/v1/auth/signup)
	PostApiV1AuthSignup(w http.ResponseWriter, r *http.Request)
	// Example protected endpoint
	// (GET /protected)
	GetProtected(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiV1AuthSignin operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthSignin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1AuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthSignup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthSignup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProtected operation middleware
func (siw *ServerInterfaceWrapper) GetProtected(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProtected(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/signin", wrapper.PostApiV1AuthSignin)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/auth/signup", wrapper.PostApiV1AuthSignup)
	m.HandleFunc("GET "+options.BaseURL+"/protected", wrapper.GetProtected)

	return m
}

type PostApiV1AuthSigninRequestObject struct {
	Body *PostApiV1AuthSigninJSONRequestBody
}

type PostApiV1AuthSigninResponseObject interface {
	VisitPostApiV1AuthSigninResponse(w http.ResponseWriter) error
}

type PostApiV1AuthSignin200JSONResponse AuthToken

func (response PostApiV1AuthSignin200JSONResponse) VisitPostApiV1AuthSigninResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignin401JSONResponse Error

func (response PostApiV1AuthSignin401JSONResponse) VisitPostApiV1AuthSigninResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignin500JSONResponse Error

func (response PostApiV1AuthSignin500JSONResponse) VisitPostApiV1AuthSigninResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignupRequestObject struct {
	Body *PostApiV1AuthSignupJSONRequestBody
}

type PostApiV1AuthSignupResponseObject interface {
	VisitPostApiV1AuthSignupResponse(w http.ResponseWriter) error
}

type PostApiV1AuthSignup201JSONResponse User

func (response PostApiV1AuthSignup201JSONResponse) VisitPostApiV1AuthSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignup400JSONResponse Error

func (response PostApiV1AuthSignup400JSONResponse) VisitPostApiV1AuthSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignup409JSONResponse Error

func (response PostApiV1AuthSignup409JSONResponse) VisitPostApiV1AuthSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1AuthSignup500JSONResponse Error

func (response PostApiV1AuthSignup500JSONResponse) VisitPostApiV1AuthSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProtectedRequestObject struct {
}

type GetProtectedResponseObject interface {
	VisitGetProtectedResponse(w http.ResponseWriter) error
}

type GetProtected200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetProtected200JSONResponse) VisitGetProtectedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProtected401JSONResponse Error

func (response GetProtected401JSONResponse) VisitGetProtectedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProtected403JSONResponse Error

func (response GetProtected403JSONResponse) VisitGetProtectedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate user
	// (POST /api/v1/auth/signin)
	PostApiV1AuthSignin(ctx context.Context, request PostApiV1AuthSigninRequestObject) (PostApiV1AuthSigninResponseObject, error)
	// Register new user
	// (POST /api/v1/auth/signup)
	PostApiV1AuthSignup(ctx context.Context, request PostApiV1AuthSignupRequestObject) (PostApiV1AuthSignupResponseObject, error)
	// Example protected endpoint
	// (GET /protected)
	GetProtected(ctx context.Context, request GetProtectedRequestObject) (GetProtectedResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostApiV1AuthSignin operation middleware
func (sh *strictHandler) PostApiV1AuthSignin(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthSigninRequestObject

	var body PostApiV1AuthSigninJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthSignin(ctx, request.(PostApiV1AuthSigninRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthSignin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthSigninResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthSigninResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1AuthSignup operation middleware
func (sh *strictHandler) PostApiV1AuthSignup(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1AuthSignupRequestObject

	var body PostApiV1AuthSignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1AuthSignup(ctx, request.(PostApiV1AuthSignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1AuthSignup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1AuthSignupResponseObject); ok {
		if err := validResponse.VisitPostApiV1AuthSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProtected operation middleware
func (sh *strictHandler) GetProtected(w http.ResponseWriter, r *http.Request) {
	var request GetProtectedRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProtected(ctx, request.(GetProtectedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProtected")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProtectedResponseObject); ok {
		if err := validResponse.VisitGetProtectedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW72/bNhD9V7TbPiqWZC3Dom9u0RYyhs1oknbYEAyMeJGYSiRHnpK6gf73gaL8Q7Ww",
	"pakb7JvFH/fu3r139AMUqtFKoiQL2QPYosKG9T8XLVUX6gNK96GN0mhIYL+FH7Uwm5+s0TVCBvN4np4k",
	"85M0uZin2elZdnr2B4Rwo0zDCDLgjPCERIMQAq21u2LJCFlCFwJtgHbxcL2srt8U4jexzC8/5cmvIre5",
	"fHtavMx/yj/o39+9XJ7NZrPDaN12RV3fYkEu/itjlJkoZLO8g83lHasFDwqDHCUJVttJCIN/t8Igh+zP",
	"IczVBO6lxQnYwiAj5H85Xh4eyZDgo7NtK/jUsdaikazBcVG3qpJc4X8W0sfchgj3Ez2srgvBYtEaQetz",
	"Jxtf2wtkBo0Tj/u67r9eb7Jevr+A0IvMRfK7u6wqIg2dCyzkjXL3OdrCCE1CSchgscqDe0FVsHx/EbCW",
	"KteggrndgEkeuMyDhklWYoOSXGBBPQGL8eHFKocQ7tBYHziZxbPY0ac0SqYFZJDO4lkKIWhGVV9YxLSI",
	"7pLI4UZWlFJ4Zyjbd9H1tw+ec8hgpSwttHiXOOBzf9hTjZZeKL7uZaAkuTSzB2Ba10Ny0a1VcufFQ/Vo",
	"Zu29MnzcYktGyXI17CXz9Lt9823vHF0ye2rZgkxoZXSLTIv9gtVKWl/VPI6/iJMfDN5ABt9HuwEWDdMr",
	"2o2uHvgzEY2lYNuiQGtv2tpx8WOcHC0LP3MmMpgaMV0Ip0dk4F+wyfWrrgMcjoRg26ZhZj3mBns3ufaz",
	"0rpGj3mDK3fzwBOt/gJPtPponsCGiXo0IP3KhNy/0j6NkL+gLN14+/kJZtq7nj7FWuFQ2NMsdjxx9w/b",
	"hL7cejA8G3veqtfeXfHzuUtI3ZJHPfv2qJdDrwJWG2R8HeBHYen/4uu3WApLaAKJ94/ytTaKsCDsXVLi",
	"hJvfIK22h75ylo+93KC1rPzMQfuTiQebyI/473dI1blX5bON+0vpxqMy4hNyD5p+e9DXylwLzvsncF8J",
	"rzyjwbbBAUqulfBkDpLYNfaq67runwAAAP//yxEhaSUMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
