//go:build go1.22

// Package todo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package todo

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for WeAll.
const (
	Dasha  WeAll = "Dasha"
	IPA    WeAll = "IPA"
	Kirill WeAll = "Kirill"
	Shiki  WeAll = "Shiki"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Task defines model for Task.
type Task struct {
	CreatedBy   WeAll              `json:"created_by"`
	Description *string            `json:"description"`
	DoBefore    time.Time          `json:"do_before"`
	Doer        WeAll              `json:"doer"`
	Done        bool               `json:"done"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Range       *int               `json:"range"`
	Repeatable  bool               `json:"repeatable"`
}

// TodosResponse defines model for TodosResponse.
type TodosResponse struct {
	Tasks []Task `json:"tasks"`
}

// WeAll defines model for WeAll.
type WeAll string

// CreateNewTaskJSONRequestBody defines body for CreateNewTask for application/json ContentType.
type CreateNewTaskJSONRequestBody = Task

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Todo list
	// (GET /api/v1/todo)
	GetAllTodos(w http.ResponseWriter, r *http.Request)
	// Creates a new task
	// (POST /api/v1/todo)
	CreateNewTask(w http.ResponseWriter, r *http.Request)
	// Get task by todo_id
	// (GET /api/v1/todo/{todo_id})
	GetTaskByID(w http.ResponseWriter, r *http.Request, todoId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAllTodos operation middleware
func (siw *ServerInterfaceWrapper) GetAllTodos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllTodos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNewTask operation middleware
func (siw *ServerInterfaceWrapper) CreateNewTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNewTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskByID operation middleware
func (siw *ServerInterfaceWrapper) GetTaskByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "todo_id" -------------
	var todoId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "todo_id", r.PathValue("todo_id"), &todoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "todo_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskByID(w, r, todoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/todo", wrapper.GetAllTodos)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/todo", wrapper.CreateNewTask)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/todo/{todo_id}", wrapper.GetTaskByID)

	return m
}

type GetAllTodosRequestObject struct {
}

type GetAllTodosResponseObject interface {
	VisitGetAllTodosResponse(w http.ResponseWriter) error
}

type GetAllTodos200JSONResponse TodosResponse

func (response GetAllTodos200JSONResponse) VisitGetAllTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTodos500JSONResponse ErrorResponse

func (response GetAllTodos500JSONResponse) VisitGetAllTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateNewTaskRequestObject struct {
	Body *CreateNewTaskJSONRequestBody
}

type CreateNewTaskResponseObject interface {
	VisitCreateNewTaskResponse(w http.ResponseWriter) error
}

type CreateNewTask201JSONResponse struct {
	TaskId openapi_types.UUID `json:"task_id"`
}

func (response CreateNewTask201JSONResponse) VisitCreateNewTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateNewTask500JSONResponse ErrorResponse

func (response CreateNewTask500JSONResponse) VisitCreateNewTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByIDRequestObject struct {
	TodoId openapi_types.UUID `json:"todo_id"`
}

type GetTaskByIDResponseObject interface {
	VisitGetTaskByIDResponse(w http.ResponseWriter) error
}

type GetTaskByID200JSONResponse Task

func (response GetTaskByID200JSONResponse) VisitGetTaskByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskByID404Response struct {
}

func (response GetTaskByID404Response) VisitGetTaskByIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetTaskByID500JSONResponse ErrorResponse

func (response GetTaskByID500JSONResponse) VisitGetTaskByIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Todo list
	// (GET /api/v1/todo)
	GetAllTodos(ctx context.Context, request GetAllTodosRequestObject) (GetAllTodosResponseObject, error)
	// Creates a new task
	// (POST /api/v1/todo)
	CreateNewTask(ctx context.Context, request CreateNewTaskRequestObject) (CreateNewTaskResponseObject, error)
	// Get task by todo_id
	// (GET /api/v1/todo/{todo_id})
	GetTaskByID(ctx context.Context, request GetTaskByIDRequestObject) (GetTaskByIDResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAllTodos operation middleware
func (sh *strictHandler) GetAllTodos(w http.ResponseWriter, r *http.Request) {
	var request GetAllTodosRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTodos(ctx, request.(GetAllTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTodos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAllTodosResponseObject); ok {
		if err := validResponse.VisitGetAllTodosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNewTask operation middleware
func (sh *strictHandler) CreateNewTask(w http.ResponseWriter, r *http.Request) {
	var request CreateNewTaskRequestObject

	var body CreateNewTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNewTask(ctx, request.(CreateNewTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNewTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateNewTaskResponseObject); ok {
		if err := validResponse.VisitCreateNewTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTaskByID operation middleware
func (sh *strictHandler) GetTaskByID(w http.ResponseWriter, r *http.Request, todoId openapi_types.UUID) {
	var request GetTaskByIDRequestObject

	request.TodoId = todoId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskByID(ctx, request.(GetTaskByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTaskByIDResponseObject); ok {
		if err := validResponse.VisitGetTaskByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUXU8bOxD9K9bcK92XvdlwgZd9C3BVRZUqVFr1AaHIWU8Sg9d2x17oKtr/Xnk2hCxZ",
	"GipRiRdw1vNx5pw5XkPpKu8s2higWEMoV1hJPv5P5OgzBu9swPTBk/NIUSNfY7rmww9ZeYNQdBmiwhDk",
	"EiGD2Pj0OUTSdgltmwHh91oTKiiuNwVutmFufotlhDaDLzLc7TcsCWVENZs36dffhAso4K/8CX++AZ9/",
	"w4kxqZDCUJL2UTubcmxtjJwnqJFq3MOXgXKzOS4c8bgLR5WMUICSEf+NuhoYKaUgvR6Ps1x6U2XunEFp",
	"041WvZZ1rdVQNysr7HN+btCKUsZ/gvDODeWQtMtnSYQeZRR4j9SIU6FkEyB7iR5tIy6RuBTndTH7UzzT",
	"lydgwBuWdvnt1cp2td2w9Ih7cD+ccuHlzYwy3PFBR6zCIXF42dptF0kkm71ZupJDWDptE7u2rlLohQwr",
	"CRl81KSNgQymlxPI4Gql7/ROha0pkvh24Ri4jizP14AkJpdTyOAeKfD2wtFoPBqnjs6jlV5DAcej8egY",
	"MvAyrnjOXHqd3x/l0SkuuMSY/iVyZDLBVEEBHzBOjGEOWYaORs7/bzxmpzkb0XKq9N7okpPz29DZqGPu",
	"IK89kXjOnh3hqi5LDGFRG0HbsAxO3xBD/wkbwDC1EclKY0T3GqWIUFeVpKZjSqQxhNGBxfYuDBB6zsv7",
	"CR94lbrFwRDPnGrejk3e0v5aJpe2ewoe/VbPfefMXvUUDfgjJd4McJygiyexG7Ex+zsTu1MxCCksPojY",
	"8Z31LJWv09+ZVu2vzJXmPWumF2xMkhVGpADF9Rp0QpHM+vgwFrApCM91zXaGPiTFzZ908XbvDoi60FZ1",
	"mp6MT1LVgXjroli42qp36PMkuJg34lGQtm3bnwEAAP//cE0mjR0JAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
