// Code generated by generator, DO NOT EDIT.
package user

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// CreateUser inserts a new User into the database.
func (r *CommandRepository) Create(ctx context.Context, user *User) error {
	model := Converter(*user)
	query, args := sq.Insert(TableUser).
		Columns(ColumnUserID, ColumnUserName, ColumnUserEmail, ColumnUserHashedPassword, ColumnUserCreatedAt, ColumnUserUpdatedAt).
		Values(model.Values()...).PlaceholderFormat(sq.Question).MustSql()

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("failed to exec create query %s with args %v error = %w", query, args, err)
	}
	return nil
}
