// Code generated by generator, DO NOT EDIT.
package user

import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
)

// GetUser retrieves a User by ID.
func (r *CommandRepository) Get(ctx context.Context, opts ...FilterOpt) (*User, error) {
	b := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).
		From(TableUser).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)

	query, args := b.MustSql()

	var user User
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.HashedPassword,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w", query, args, err)
	}

	return &user, err
}
func (r *QueryRepository) Get(ctx context.Context, opts ...FilterOpt) (*User, error) {
	b := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).
		From(TableUser).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)

	query, args := b.MustSql()

	var user User
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.HashedPassword,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w", query, args, err)
	}

	return &user, err
}

// GetManyUser retrieves a User by filter.
func (r *CommandRepository) GetMany(ctx context.Context, opts ...FilterOpt) (Users, error) {
	b := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).From(TableUser).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)
	query, args := b.MustSql()
	var users Users

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()

	var userModel UserModel
	for rows.Next() {
		err := rows.Scan(
			&userModel.ID,
			&userModel.Name,
			&userModel.Email,
			&userModel.HashedPassword,
			&userModel.CreatedAt,
			&userModel.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		users = append(users, ReverseConverter(userModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return users, err
}

// GetManyUser retrieves a User by filter.
func (r *QueryRepository) GetMany(ctx context.Context, opts ...FilterOpt) (Users, error) {
	b := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).From(TableUser).PlaceholderFormat(sq.Question)

	f := &Filter{}
	for i := 0; i < len(opts); i++ {
		opts[i](f)
	}
	b = ApplyWhere(b, *f)
	query, args := b.MustSql()
	var users Users

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()

	var userModel UserModel
	for rows.Next() {
		err := rows.Scan(
			&userModel.ID,
			&userModel.Name,
			&userModel.Email,
			&userModel.HashedPassword,
			&userModel.CreatedAt,
			&userModel.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		users = append(users, ReverseConverter(userModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return users, err
}
