//Code generated by generator, DO NOT EDIT.
package user


import (
	"context"
	"fmt"

	sq "github.com/Masterminds/squirrel"
	"github.com/google/uuid"
)


// GetUser retrieves a User by ID.
func (r *Repository) Get(ctx context.Context,  id uuid.UUID) (*User, error) {
	query, args := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).
	From(TableUser).
	Where(sq.Eq{ColumnUserID: id}).PlaceholderFormat(sq.Question).MustSql()

	var user User
	err := r.db.QueryRow(ctx, query, args...).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.HashedPassword,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get query %s with args %v error = %w" , query, args, err)
	}

	return &user, err
}


// GetManyUser retrieves a User by filter.
func (r *Repository) GetMany(ctx context.Context, f Filter) (Users, error) {
b := sq.Select(
		ColumnUserID,
		ColumnUserName,
		ColumnUserEmail,
		ColumnUserHashedPassword,
		ColumnUserCreatedAt,
		ColumnUserUpdatedAt,
	).From(TableUser).PlaceholderFormat(sq.Question)

	b = ApplyWhere(b, f)

    query, args := 	b.MustSql()

    var users Users

	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying database: %w", err)
	}
	defer rows.Close()


	var userModel UserModel
	for rows.Next() {
		err := rows.Scan(
			&userModel.ID,
			&userModel.Name,
			&userModel.Email,
			&userModel.HashedPassword,
			&userModel.CreatedAt,
			&userModel.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("error scanning row: %w", err)
		}
		users = append(users, ReverseConverter(userModel))
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("error iterating rows: %w", rows.Err())
	}

	return users, err
}


