//Code generated by generator, DO NOT EDIT.
package user

import (
	sq "github.com/Masterminds/squirrel"
	"sort"
	common "github.com/AugustineAurelius/fuufu/pkg/common"
    "time"
    "github.com/google/uuid"
)



type Repository struct{
	db common.Querier
}

func New(db common.Querier) *Repository {
	return &Repository{
		db: db,
	}
}

// UserFiler represents the User filter.
type Filter struct {
  id *uuid.UUID
  notid *uuid.UUID
  gtid *uuid.UUID
  ltid *uuid.UUID
  gteqid *uuid.UUID
  lteqid *uuid.UUID
  ids []uuid.UUID
  name *string
  notname *string
  gtname *string
  ltname *string
  gteqname *string
  lteqname *string
  names []string
  email *string
  notemail *string
  gtemail *string
  ltemail *string
  gteqemail *string
  lteqemail *string
  emails []string
  hashedpassword *string
  nothashedpassword *string
  gthashedpassword *string
  lthashedpassword *string
  gteqhashedpassword *string
  lteqhashedpassword *string
  hashedpasswords []string
  createdat *time.Time
  notcreatedat *time.Time
  gtcreatedat *time.Time
  ltcreatedat *time.Time
  gteqcreatedat *time.Time
  lteqcreatedat *time.Time
  createdats []time.Time
  updatedat **time.Time
  notupdatedat **time.Time
  gtupdatedat **time.Time
  ltupdatedat **time.Time
  gtequpdatedat **time.Time
  ltequpdatedat **time.Time
  updatedats []*time.Time
}

type FilterOpt func(f *Filter)

func NewFilter(opts ...FilterOpt) Filter{
	f := &Filter{}
	for _, opt := range opts {
		opt(f)
	}
	return *f
}
func WithID(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.id = &id
	}
}
func WithIDNot(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.notid = &id
	}
}
func WithIDMoreThen(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.gtid = &id
	}
}
func WithIDLowerThen(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.ltid = &id
	}
}
func WithIDMoreOrEqualThen(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.gteqid = &id
	}
}
func WithIDLowerOrEqualThen(id uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.lteqid = &id
	}
}
func WithIDs (ids ...uuid.UUID)  FilterOpt {
	return func(f *Filter) {
		f.ids = append(f.ids, ids...)
	}
}
func WithName(name string)  FilterOpt {
	return func(f *Filter) {
		f.name = &name
	}
}
func WithNameNot(name string)  FilterOpt {
	return func(f *Filter) {
		f.notname = &name
	}
}
func WithNameMoreThen(name string)  FilterOpt {
	return func(f *Filter) {
		f.gtname = &name
	}
}
func WithNameLowerThen(name string)  FilterOpt {
	return func(f *Filter) {
		f.ltname = &name
	}
}
func WithNameMoreOrEqualThen(name string)  FilterOpt {
	return func(f *Filter) {
		f.gteqname = &name
	}
}
func WithNameLowerOrEqualThen(name string)  FilterOpt {
	return func(f *Filter) {
		f.lteqname = &name
	}
}
func WithNames (names ...string)  FilterOpt {
	return func(f *Filter) {
		f.names = append(f.names, names...)
	}
}
func WithEmail(email string)  FilterOpt {
	return func(f *Filter) {
		f.email = &email
	}
}
func WithEmailNot(email string)  FilterOpt {
	return func(f *Filter) {
		f.notemail = &email
	}
}
func WithEmailMoreThen(email string)  FilterOpt {
	return func(f *Filter) {
		f.gtemail = &email
	}
}
func WithEmailLowerThen(email string)  FilterOpt {
	return func(f *Filter) {
		f.ltemail = &email
	}
}
func WithEmailMoreOrEqualThen(email string)  FilterOpt {
	return func(f *Filter) {
		f.gteqemail = &email
	}
}
func WithEmailLowerOrEqualThen(email string)  FilterOpt {
	return func(f *Filter) {
		f.lteqemail = &email
	}
}
func WithEmails (emails ...string)  FilterOpt {
	return func(f *Filter) {
		f.emails = append(f.emails, emails...)
	}
}
func WithHashedPassword(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.hashedpassword = &hashedpassword
	}
}
func WithHashedPasswordNot(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.nothashedpassword = &hashedpassword
	}
}
func WithHashedPasswordMoreThen(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.gthashedpassword = &hashedpassword
	}
}
func WithHashedPasswordLowerThen(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.lthashedpassword = &hashedpassword
	}
}
func WithHashedPasswordMoreOrEqualThen(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.gteqhashedpassword = &hashedpassword
	}
}
func WithHashedPasswordLowerOrEqualThen(hashedpassword string)  FilterOpt {
	return func(f *Filter) {
		f.lteqhashedpassword = &hashedpassword
	}
}
func WithHashedPasswords (hashedpasswords ...string)  FilterOpt {
	return func(f *Filter) {
		f.hashedpasswords = append(f.hashedpasswords, hashedpasswords...)
	}
}
func WithCreatedAt(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.createdat = &createdat
	}
}
func WithCreatedAtNot(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.notcreatedat = &createdat
	}
}
func WithCreatedAtMoreThen(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.gtcreatedat = &createdat
	}
}
func WithCreatedAtLowerThen(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.ltcreatedat = &createdat
	}
}
func WithCreatedAtMoreOrEqualThen(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.gteqcreatedat = &createdat
	}
}
func WithCreatedAtLowerOrEqualThen(createdat time.Time)  FilterOpt {
	return func(f *Filter) {
		f.lteqcreatedat = &createdat
	}
}
func WithCreatedAts (createdats ...time.Time)  FilterOpt {
	return func(f *Filter) {
		f.createdats = append(f.createdats, createdats...)
	}
}
func WithUpdatedAt(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.updatedat = &updatedat
	}
}
func WithUpdatedAtNot(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.notupdatedat = &updatedat
	}
}
func WithUpdatedAtMoreThen(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.gtupdatedat = &updatedat
	}
}
func WithUpdatedAtLowerThen(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.ltupdatedat = &updatedat
	}
}
func WithUpdatedAtMoreOrEqualThen(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.gtequpdatedat = &updatedat
	}
}
func WithUpdatedAtLowerOrEqualThen(updatedat *time.Time)  FilterOpt {
	return func(f *Filter) {
		f.ltequpdatedat = &updatedat
	}
}
func WithUpdatedAts (updatedats ...*time.Time)  FilterOpt {
	return func(f *Filter) {
		f.updatedats = append(f.updatedats, updatedats...)
	}
}

func ApplyWhere[B interface {
    Where(pred interface{}, args ...interface{}) B
}](b B,f Filter) B {
	if f.id != nil {
      b = b.Where(sq.Eq{ColumnUserID: *f.id})
    }
	if f.notid != nil {
      b = b.Where(sq.NotEq{ColumnUserID: *f.id})
    }
	if f.ltid != nil {
      b = b.Where(sq.Lt{ColumnUserID: *f.id})
    }
	if f.gtid != nil {
      b = b.Where(sq.Gt{ColumnUserID: *f.id})
    }
	if f.lteqid != nil {
      b = b.Where(sq.LtOrEq{ColumnUserID: *f.id})
    }
	if f.gteqid != nil {
      b = b.Where(sq.GtOrEq{ColumnUserID: *f.id})
    }
	if f.ids != nil {
      b = b.Where(sq.Eq{ColumnUserID: f.ids})
    }
	if f.name != nil {
      b = b.Where(sq.Eq{ColumnUserName: *f.name})
    }
	if f.notname != nil {
      b = b.Where(sq.NotEq{ColumnUserName: *f.name})
    }
	if f.ltname != nil {
      b = b.Where(sq.Lt{ColumnUserName: *f.name})
    }
	if f.gtname != nil {
      b = b.Where(sq.Gt{ColumnUserName: *f.name})
    }
	if f.lteqname != nil {
      b = b.Where(sq.LtOrEq{ColumnUserName: *f.name})
    }
	if f.gteqname != nil {
      b = b.Where(sq.GtOrEq{ColumnUserName: *f.name})
    }
	if f.names != nil {
      b = b.Where(sq.Eq{ColumnUserName: f.names})
    }
	if f.email != nil {
      b = b.Where(sq.Eq{ColumnUserEmail: *f.email})
    }
	if f.notemail != nil {
      b = b.Where(sq.NotEq{ColumnUserEmail: *f.email})
    }
	if f.ltemail != nil {
      b = b.Where(sq.Lt{ColumnUserEmail: *f.email})
    }
	if f.gtemail != nil {
      b = b.Where(sq.Gt{ColumnUserEmail: *f.email})
    }
	if f.lteqemail != nil {
      b = b.Where(sq.LtOrEq{ColumnUserEmail: *f.email})
    }
	if f.gteqemail != nil {
      b = b.Where(sq.GtOrEq{ColumnUserEmail: *f.email})
    }
	if f.emails != nil {
      b = b.Where(sq.Eq{ColumnUserEmail: f.emails})
    }
	if f.hashedpassword != nil {
      b = b.Where(sq.Eq{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.nothashedpassword != nil {
      b = b.Where(sq.NotEq{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.lthashedpassword != nil {
      b = b.Where(sq.Lt{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.gthashedpassword != nil {
      b = b.Where(sq.Gt{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.lteqhashedpassword != nil {
      b = b.Where(sq.LtOrEq{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.gteqhashedpassword != nil {
      b = b.Where(sq.GtOrEq{ColumnUserHashedPassword: *f.hashedpassword})
    }
	if f.hashedpasswords != nil {
      b = b.Where(sq.Eq{ColumnUserHashedPassword: f.hashedpasswords})
    }
	if f.createdat != nil {
      b = b.Where(sq.Eq{ColumnUserCreatedAt: *f.createdat})
    }
	if f.notcreatedat != nil {
      b = b.Where(sq.NotEq{ColumnUserCreatedAt: *f.createdat})
    }
	if f.ltcreatedat != nil {
      b = b.Where(sq.Lt{ColumnUserCreatedAt: *f.createdat})
    }
	if f.gtcreatedat != nil {
      b = b.Where(sq.Gt{ColumnUserCreatedAt: *f.createdat})
    }
	if f.lteqcreatedat != nil {
      b = b.Where(sq.LtOrEq{ColumnUserCreatedAt: *f.createdat})
    }
	if f.gteqcreatedat != nil {
      b = b.Where(sq.GtOrEq{ColumnUserCreatedAt: *f.createdat})
    }
	if f.createdats != nil {
      b = b.Where(sq.Eq{ColumnUserCreatedAt: f.createdats})
    }
	if f.updatedat != nil {
      b = b.Where(sq.Eq{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.notupdatedat != nil {
      b = b.Where(sq.NotEq{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.ltupdatedat != nil {
      b = b.Where(sq.Lt{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.gtupdatedat != nil {
      b = b.Where(sq.Gt{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.ltequpdatedat != nil {
      b = b.Where(sq.LtOrEq{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.gtequpdatedat != nil {
      b = b.Where(sq.GtOrEq{ColumnUserUpdatedAt: *f.updatedat})
    }
	if f.updatedats != nil {
      b = b.Where(sq.Eq{ColumnUserUpdatedAt: f.updatedats})
    }
  return b
}

type UpdateOpt func(u *Update)

// UserUpdate represents the User update struct.
type Update struct {
  id *uuid.UUID
  name *string
  email *string
  hashedpassword *string
  createdat *time.Time
  updatedat **time.Time
}

func NewUpdate(opts ...UpdateOpt) Update{
	u := &Update{}
	for _, opt := range opts {
		opt(u)
	}
	return *u
}
func WithUpdateID(id uuid.UUID)  UpdateOpt {
	return func(f *Update) {
		f.id = &id
	}
}
func WithUpdateName(name string)  UpdateOpt {
	return func(f *Update) {
		f.name = &name
	}
}
func WithUpdateEmail(email string)  UpdateOpt {
	return func(f *Update) {
		f.email = &email
	}
}
func WithUpdateHashedPassword(hashedpassword string)  UpdateOpt {
	return func(f *Update) {
		f.hashedpassword = &hashedpassword
	}
}
func WithUpdateCreatedAt(createdat time.Time)  UpdateOpt {
	return func(f *Update) {
		f.createdat = &createdat
	}
}
func WithUpdateUpdatedAt(updatedat *time.Time)  UpdateOpt {
	return func(f *Update) {
		f.updatedat = &updatedat
	}
}

func ApplySet[B interface {
    Set(column string, value interface{}) B
}] (b B, f Update) B {
	if f.id != nil {
      b = b.Set(ColumnUserID, *f.id)
    }
	if f.name != nil {
      b = b.Set(ColumnUserName, *f.name)
    }
	if f.email != nil {
      b = b.Set(ColumnUserEmail, *f.email)
    }
	if f.hashedpassword != nil {
      b = b.Set(ColumnUserHashedPassword, *f.hashedpassword)
    }
	if f.createdat != nil {
      b = b.Set(ColumnUserCreatedAt, *f.createdat)
    }
	if f.updatedat != nil {
      b = b.Set(ColumnUserUpdatedAt, *f.updatedat)
    }

  return b
}

type Users []User
func (s Users) ToIDs ()  []uuid.UUID {
	output := make([]uuid.UUID, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].ID)
	}
	return output
}
func (s Users) ToNames ()  []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].Name)
	}
	return output
}
func (s Users) ToEmails ()  []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].Email)
	}
	return output
}
func (s Users) ToHashedPasswords ()  []string {
	output := make([]string, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].HashedPassword)
	}
	return output
}
func (s Users) ToCreatedAts ()  []time.Time {
	output := make([]time.Time, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].CreatedAt)
	}
	return output
}
func (s Users) ToUpdatedAts ()  []*time.Time {
	output := make([]*time.Time, 0, len(s))
	for i := 0; i < len(s); i++{
    output = append(output, s[i].UpdatedAt)
	}
	return output
}
func (s Users) FindByID (finder uuid.UUID)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].ID  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) FindByName (finder string)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].Name  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) FindByEmail (finder string)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].Email  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) FindByHashedPassword (finder string)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].HashedPassword  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) FindByCreatedAt (finder time.Time)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].CreatedAt  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) FindByUpdatedAt (finder *time.Time)  (User, bool) {
	for i := 0; i < len(s); i++{
		if s[i].UpdatedAt  == finder {
			return s[i], true 
		}
	}
	return   User {}, false
}
func (s Users) SortByName (asc bool)  Users {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].Name < s[j].Name
		})
		return s
	}	
	sort.Slice(s, func(i, j int) bool {
		return s[i].Name > s[j].Name
	})
	return  s
}
func (s Users) SortByEmail (asc bool)  Users {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].Email < s[j].Email
		})
		return s
	}	
	sort.Slice(s, func(i, j int) bool {
		return s[i].Email > s[j].Email
	})
	return  s
}
func (s Users) SortByHashedPassword (asc bool)  Users {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].HashedPassword < s[j].HashedPassword
		})
		return s
	}	
	sort.Slice(s, func(i, j int) bool {
		return s[i].HashedPassword > s[j].HashedPassword
	})
	return  s
}
func (s Users) SortByCreatedAt (asc bool)  Users {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].CreatedAt.Before( s[j].CreatedAt)
		})
		return s
	}	
	sort.Slice(s, func(i, j int) bool {
		return s[i].CreatedAt.After(s[j].CreatedAt)
	})
	return  s
}
func (s Users) SortByUpdatedAt (asc bool)  Users {
	if asc {
		sort.Slice(s, func(i, j int) bool {
			return s[i].UpdatedAt.Before( *s[j].UpdatedAt)
		})
		return s
	}	
	sort.Slice(s, func(i, j int) bool {
		return s[i].UpdatedAt.After( *s[j].UpdatedAt)
	})
	return  s
}




func (s Users) FilterFunc(f func(i User) bool)  Users {
	output := make(Users, 0, len(s))
	for i := 0; i < len(s); i++{ 
		if f(s[i]) {
			output = append(output, s[i])
		}
	}
	return output
}
func (s Users) GetFirstID()  (*uuid.UUID, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].ID, true
}
func (s Users) GetFirstName()  (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Name, true
}
func (s Users) GetFirstEmail()  (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].Email, true
}
func (s Users) GetFirstHashedPassword()  (*string, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].HashedPassword, true
}
func (s Users) GetFirstCreatedAt()  (*time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].CreatedAt, true
}
func (s Users) GetFirstUpdatedAt()  (**time.Time, bool) {
	if len(s) < 1 {
		return nil, false
	}
	return &s[0].UpdatedAt, true
}



func (s Users) GetFirst()  (User, bool) {
	if len(s) < 1 {
		return User{}, false
	}
	return s[0], true
}


