//Code generated by generator, DO NOT EDIT.
package user

import (
    "time"
    "github.com/google/uuid"
)

// Table and column name constants for User
const (
	TableUser = "users"
	ColumnUserID = "id"
	ColumnUserName = "name"
	ColumnUserEmail = "email"
	ColumnUserHashedPassword = "hashed_password"
	ColumnUserCreatedAt = "created_at"
	ColumnUserUpdatedAt = "updated_at"
)



// User represents the User message.
type UserModel struct {
	
		ID string
	
	
		Name string
	
	
		Email string
	
	
		HashedPassword string
	
	
		CreatedAt time.Time
	
	
		UpdatedAt *time.Time
	
}

func (m UserModel) Values() []any {
	return []any {
			m.ID,
			m.Name,
			m.Email,
			m.HashedPassword,
			m.CreatedAt,
			m.UpdatedAt,
	}
}

func Converter(user User) UserModel {
	return UserModel {
			
		ID: user.ID.String(),
			
			
		Name: user.Name, 
			
			
		Email: user.Email, 
			
			
		HashedPassword: user.HashedPassword, 
			
			
		CreatedAt: user.CreatedAt, 
			
			
		UpdatedAt: user.UpdatedAt, 
			
	}
}

func ReverseConverter(userModel UserModel) User {
	return User {
			
		ID: uuid.MustParse(userModel.ID),
			
			
		Name: userModel.Name, 
			
			
		Email: userModel.Email, 
			
			
		HashedPassword: userModel.HashedPassword, 
			
			
		CreatedAt: userModel.CreatedAt, 
			
			
		UpdatedAt: userModel.UpdatedAt, 
				
	}
}
