openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  api/v1/todo:
    get: 
      summary: Get Todo list
      operationId: GetAllTodos
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodosResponse'
        '500':
          description: Internall error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    
  schemas:
    WeAll:
      type: string
      enum: [Dasha,Kirill,IPA,Shiki]

    Task:
      type: object
      required: [name, doer, do_before, repeatable, created_by, done, range]
      properties:
        name:
          type: string
          example: Clen cat's poo
        doer: 
          $ref: '#/components/schemas/WeAll'
        description:
          type: string
          nullable: true
        do_before:
          type: string
          format: "date-time"
        repeatable:
          type: boolean
        created_by:
          $ref: '#/components/schemas/WeAll'
        done:
          type: boolean
        range:
          type: number
          example: repeat every 5 days
          nullable: true

    TodosResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
      required:
        - tasks


    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error message"
      required:
        - error
